# Generated by Django 5.0.6 on 2024-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_methods_alter_algorithms_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methods',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
