# Generated by Django 5.0.6 on 2024-05-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_methods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithms',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='algorithms',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
    ]
