# Generated by Django 5.0.6 on 2024-05-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_algorithms_description_alter_algorithms_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='methods',
            name='sort',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Сортировка'),
        ),
    ]
