# Generated by Django 5.0.6 on 2024-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_methods_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithms',
            options={'ordering': ('sort', 'title'), 'verbose_name': 'Алгоритм', 'verbose_name_plural': 'Алгоритмы'},
        ),
        migrations.AlterModelOptions(
            name='methods',
            options={'ordering': ('sort', 'title'), 'verbose_name': 'Метод', 'verbose_name_plural': 'Методы'},
        ),
        migrations.AddField(
            model_name='algorithms',
            name='sort',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Сортировка'),
        ),
    ]
