# Generated by Django 5.0.6 on 2024-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_algorithms_options_alter_methods_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithms',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
