# Generated by Django 5.0.6 on 2024-05-22 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_algorithms_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeluser',
            name='encrypt',
        ),
        migrations.AddField(
            model_name='encrypts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
