# Generated by Django 5.0.6 on 2024-05-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_modeluser_encrypt_encrypts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='encrypts',
            name='key',
            field=models.TextField(verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='encrypts',
            name='result',
            field=models.TextField(verbose_name='Результат'),
        ),
    ]
